PROTEUM - I/O LOG FILE
May-07-24
V 2.1 - IM
                   
Number of elements that are either odd or positive is: 0
2
8949 32 
c2 9156 32 
c8 Number of elements that are either odd or positive is: 3
2
8949 32 
fe 9156 32 
f8 Number of elements that are either odd or positive is: 1
2
8949 32 
fe 9156 32 
f8 Number of elements that are either odd or positive is: 1
2
8949 32 
fe 9156 32 
f8 Number of elements that are either odd or positive is: 1
2
8949 32 
fe 9156 32 
f8 Number of elements that are either odd or positive is: 0
2
8949 32 
f6 9156 32 
f8 Number of elements that are either odd or positive is: 0
2
8949 32 
f6 9156 32 
f8 Number of elements that are either odd or positive is: 3
2
8949 32 
fe 9156 32 
f8 Number of elements that are either odd or positive is: 0
2
8949 32 
f6 9156 32 
f8 Number of elements that are either odd or positive is: 2
2
8949 32 
fe 9156 32 
f8 Number of elements that are either odd or positive is: 0
2
8949 32 
c2 9156 32 
c8 